In [1]:
import numpy as np

In [3]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [4]:
valoraciones[0][1]

7

In [5]:
valoraciones[0,1]

7

In [10]:
valoraciones2=np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])

In [11]:
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [13]:
valoraciones2[2,1,2]

10

In [14]:
np.zeros((3,2,4,10,5))

array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 

In [15]:
valoraciones2+np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [16]:
np.mean(valoraciones2)

6.458333333333333

In [17]:
np.mean(valoraciones2,axis=0)

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [18]:
np.mean(valoraciones2,axis=1)

array([[5. , 6. , 6.5, 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

In [19]:
np.mean(valoraciones2,axis=2)

array([[7.  , 3.5 ],
       [5.  , 7.  ],
       [7.  , 9.25]])

In [20]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [21]:
np.median(df["Columna1"])

NameError: name 'df' is not defined

In [22]:
np.random.rand(2,2)

array([[0.46846782, 0.22217867],
       [0.61930003, 0.56204255]])

Numpy es un paquete orientado al análisis matemático y científico de datos, que es uno de los más populares que hay disponibles para Python. Este paquete viene incorporado dentro de la plataforma Anaconda, así que no tendremos que instalarlo. Vamos a importarlo utilizando la sintaxis estándar. Lo primero que te voy a presentar es como crear el objeto más popular de este paquete, que son los "arrays". ¿Qué es un "array"? Ahora lo veremos. Es muy parecido a una matriz. Vamos a usar estos valores y os voy a enseñar cómo se visualiza. Esto es un "numpy array". ¿Qué tenemos aquí? Tenemos básicamente una matriz con dos ejes: un eje vertical, donde tenemos cuatro columnas, y un eje horizontal, donde tenemos tres filas. ¿Cómo vamos a interpretar los datos que aquí tenemos? Voy a presentaros un ejemplo donde tenemos tres clientes, cada una de las filas, que han valorado cuatro productos, cada una de las columnas. ¿Cómo se accede a la información? Vamos a verlo. Hay dos maneras de hacerlo, os las presento ambas. La primera es esta de aquí. ¿Qué le estamos diciendo? Que queremos acceder al primer elemento de la primera dimensión y al segundo elemento de la segunda dimensión. Como podéis ver, la primera dimensión son las filas, así que vamos a coger la primera fila, y la segunda dimensión son las columnas. El segundo elemento es esta de aquí, así que estamos cogiendo el primero y el segundo, que es este siete, como aquí vemos. Esto tiene una notación alternativa que podemos hacer separando por comas. Es exactamente lo mismo. Vamos a ver que, si vamos añadiendo nuevas dimensiones, podemos ir añadiendo aquí nuevos corchetes y abajo nuevas comas. Vamos a ver un ejemplo de cómo creamos una red con más dimensiones. Os he pegado el código. Vamos a llamarle 'valoraciones2' y aquí vamos a tener tres dimensiones. Ahora vamos a verlas. Lo mostramos por pantalla, ejecutamos y ahora os explico qué es lo que vamos a tener aquí. Aquí vamos a tener lo mismo, tres clientes –uno, dos y tres–, cuatro productos, uno para cada columna, pero cada cliente habrá valorado estos productos hace un año y este año. Así, con este tipo de estructura, podemos ir incrementando la dimensionalidad de nuestros datos y podemos mantener el tipo de análisis que queremos. Como te he comentado, ahora podemos acceder a los elementos con esta sintaxis, por ejemplo, '[0,1,2]'. Nos va a mostrar el primer elemento de la primera dimensión, el segundo elemento de la segunda dimensión y el tercer elemento de la tercera dimensión. Recuerdo que el cero es el primer elemento siempre en Python. ¿Has encontrado en el "array" a qué cinco nos estamos refiriendo? Otra funcionalidad interesante que podemos utilizar es crear "arrays" vacíos. Por ejemplo, podemos usar esta función, 'zeros', y especificarle las dimensiones que queremos crear. Por ejemplo, vamos a crear tres dimensiones, es decir, tres números. La primera dimensión vamos a querer tres clientes, dos y cuatro, por ejemplo. Vemos que acabamos de generar la misma estructura que teníamos antes pero vacía. Esto, como te puedes imaginar, es escalable a cualquier tipo de dimensiones. Podemos ponerle 10, 5... Y si ejecutamos, vamos a ver que hemos creado un objeto difícil de interpretar, pero que tiene las dimensiones que le hemos pedido. Continuamos viendo algunas de las funcionalidades de este paquete. Vamos a ver ahora que podemos realizar operaciones entre "arrays" de los mismos tamaños. Vamos a coger 'valoraciones2' y vamos a sumarle –y aprovecho para mostrarte una nueva función–, vamos a sumarle a cada uno de los elementos un uno. Un uno porque hemos creado aquí un "array" con estas tres dimensiones y lleno de unos, así que, cuando lo ejecutemos, vamos a ver que tenemos el mismo "array" que antes, pero le hemos sumado uno a cada puntuación. Los "arrays" son una estructura muy práctica con la que trabajar, ya que podemos aplicarle muchas funciones. Por ejemplo, la media al "array" entero, y nos devuelve la media de todos los valores que podíamos encontrar aquí, el original. El resultado anterior no lo hemos guardado. Así que todas las valoraciones de todos los productos clientes y los dos años que hemos comentado antes son 6,45. Pero esto no se termina aquí, ya que podemos hacer, por ejemplo, 'valoraciones2' y especificarle en qué eje queremos que nos calcule la media. Por ejemplo, ejecutamos para primer eje. ¿Qué ha pasado aquí? Nos ha calculado, por ejemplo, este 6 es la media entre 8, 2 y 8. Este 6,66 es la media entre 2, 8 y 10, y así sucesivamente. Podemos cambiar el eje. Si hemos puesto el segundo eje, este 5 va a ser la media entre 8 y 2. El siguiente 5, entre este 8 y 2. El siguiente 9 entre el 8 y el 10. Y ya para verlos todos ejecutamos el último eje y podemos ver que las medias ahora se realizan de la siguiente manera. Este 7 es la media de todos estos valores. Este 3 y medio es la media entre todos estos valores y así vamos haciendo. Os comento algunas funciones más. Una muy interesante es este que vemos aquí, el 'reshape', que nos permite convertir una lista, por ejemplo, esta lista del uno al 12 a las dimensiones que nosotros queramos. Ejecutamos y podemos ver que lo ha partido en tres dimensiones: una, dos, tres. Tres filas, dos columnas. Tenemos que ir con cuidado de que estas dimensiones multiplicadas se ajusten al tamaño general de la lista que le hemos dado. Para terminar, comentar que podemos usar este paquete, por ejemplo, la función 'median' sobre columnas de "data frames". Ahora no lo tenemos cargado, pero podemos poner 'Columna1'. Y si ejecutásemos esto, obtendríamos la mediana. Dentro del paquete Numpy podemos encontrar el módulo 'random', que nos permite generar objetos aleatorios. Aquí lo que hemos hecho es generar un objeto con dos dimensiones, cada una dos filas y dos columnas, y nos ha generado cuatro números aleatorios entre 0 y el 1.
